/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Insides(props) {
	const { nodes, materials } = useGLTF('/insides.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides.geometry}
				material={materials.Stiching}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_1.geometry}
				material={materials['Inner Shell']}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_2.geometry}
				material={materials.Plastics}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_3.geometry}
				material={materials['Black Metal']}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_4.geometry}
				material={materials.Spring}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_5.geometry}
				material={materials.Rubber}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_6.geometry}
				material={materials['Inside Fabric']}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_7.geometry}
				material={materials['Outside Fabric']}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_8.geometry}
				material={materials.Inlays}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.insides_9.geometry}
				material={materials['Shell Plastics']}
			/>
		</group>
	)
}

useGLTF.preload('/insides.glb')
