/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'

export default function Visor(props) {
	const { nodes, materials } = useGLTF('/visor.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.visor.geometry}
				material={materials.Screw}
			/>
			<mesh castShadow receiveShadow geometry={nodes.visor_1.geometry}>
				<MeshTransmissionMaterial />
			</mesh>
		</group>
	)
}

useGLTF.preload('/visor.glb')
